[versions]
agp = "8.13.2"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.3"
activityCompose = "1.10.1"
composeBom = "2025.08.01"
appcompat = "1.7.1"
material = "1.13.0"
fbjni = "0.7.0"
nativeloader = "0.12.1"
soloader = "0.12.1"
recyclerview = "1.4.0"
viewpager2 = "1.1.0"
vosk = "0.3.70"
executorch-xnnpack = "1.0.1"
executorch-vulkan = "1.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name="appcompat", version.ref = "appcompat"}
google-material    = { group = "com.google.android.material", name = "material",  version.ref = "material" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
vosk-android = { module = "com.alphacephei:vosk-android", version.ref = "vosk" }
facebook-fbjni = { group = "com.facebook.fbjni", name = "fbjni", version.ref = "fbjni"}
facebook-nativeloader = { group = "com.facebook.soloader", name = "nativeloader", version.ref = "nativeloader"}
facebook-soloader = { group = "com.facebook.soloader", name = "soloader", version.ref= "soloader" }
executorch-xnnpack = { group = "org.pytorch", name = "executorch-android", version.ref = "executorch-xnnpack"}
executorch-vulkan = { group = "org.pytorch", name = "executorch-android-vulkan", version.ref = "executorch-vulkan"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


